language: cpp
compiler: gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y scons python-jinja2 python3
before_script:
 - sudo apt-get install -y software-properties-common
 - sudo add-apt-repository -y ppa:terry.guo/gcc-arm-embedded
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install -y gcc-arm-none-eabi
 - sudo apt-get install -y g++-4.8

script: ./check.py
